#ifndef TF_3DPING_SHARED_H
#define TF_3DPING_SHARED_H
#ifdef _WIN32
#pragma once
#endif

#define TF_3DPING_COMMAND_NAME		"tf_ping"

#define TF_3DPING_USERMSG_NAME		"TF3DPing"

#define TF_3DPING_TEAM_CONVAR_NAME	"cl_3dping_team_enabled"

#define TF_3DPING_ENABLED_CONVAR_NAME	"cl_3dping_enabled"

enum ETF3DPingType
{
	TF_3DPING_WORLD = 0,
	TF_3DPING_PLAYER,
	TF_3DPING_BUILDING,
	TF_3DPING_PICKUP_HEALTH,
	TF_3DPING_PICKUP_AMMO,
	TF_3DPING_MVM_ROBOT,
	TF_3DPING_MVM_SENTRYBUSTER,
	TF_3DPING_MVM_TANK,

	TF_3DPING_TYPE_COUNT
};

#define TF_3DPING_DEFAULT_COOLDOWN	"0.2"
#define TF_3DPING_DEFAULT_LIFETIME	"5.0"

#define TF_3DPING_POST_CLOAK_LOCKOUT	2.0f

#endif // TF_3DPING_SHARED_H
